- name: Criar o dir da app Giropops
  file: path={{item}} state=directory
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf
  register: criando_dir

- name: Copiar o arquivo de deploy da app para o host
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copar o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item_dest }}
  with_items:
    - { src: 'service_app.yml', dest: '/opt/giropops/service_app.yml'}
  register: copiar_service_file

- name: Executar o deploy da app Giropops
  shell: kubectl apply -f /opt/giropops/app-v1.yml
  register: deploy_app

- name: Criar o service da app Giropops
  shell: kubectl apply -f /opt/giropops/service_app.yml
  register: deploy_svc_app