- name: Install pip
  apt:
    name:
      - python-pip

- name: Install dependencias do modulo k8s
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiar arquivo de deploy app v1
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiar arquivo de deploy app v2
  template:
    src: app-v2.yml.j2
    dest: /opt/giropops/app-v2.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v2

- name: Deploy app-v2
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v2.yml

- name: Diminuir replicas app-v1
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v1.yml

- name: Em 3 min o app-v1 será removida. Pressione ctrl+c para cancelar
  pause:
    minutes: 3

- name: Remover app-v1
  k8s:
    state: absent
    namespace: default
    src: /opt/giropops/app-v1.yml